### ISSUE TITLE
Unable to build the app

### ISSUE THREAD

**Issue by Fen747** [RobertLowe/meteor-phaser#2]
Hi !

I added your package to a whole new meteor app. Unfortunately, I'm unable to get it started : each time I type `meteor`in the console, the cuild blocks indefinitely on the "Building for web.browser" step :/

I already had built a very simple meteor / phaser app months ago, but seems I deleted it and can't figure out what's has changed and might be leading to this problem.

FYI :
Window 10
Meteor 1.2.1

EDIT: it happens even If I simply copy / paste phaser.js in the client without using your package :/

**Comment by RobertLowe** [comment]
Well, this package hasn't changed in quite sometime... I'm not sure what's up.

Try using phaser off the CDN:

```
<head>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/phaser/2.4.4/phaser.js"></script>
</head>
```

**Comment by Fen747** [comment]
You saved me, Thanks you ! I even wasn't thinking about using a cdn ^^
